---
  sudo: false
  language: ruby
  bundler_args: --without system_tests
  script: 'bundle exec rake test'
  matrix:
    fast_finish: true
    include:
      - rvm: 2.1.10
        env: PUPPET_GEM_VERSION="~> 4.0 STRICT_VARIABLES='yes'"
  notifications:
    email: false

