---
language: ruby
rvm:
  - 2.3
script: 'bundle exec rake spec'
branches:
  only:
    - master
    - develop
env:
  - PUPPET_VERSION=4.10.9
  - PUPPET_VERSION=5.3.3
notifications:
  email: false
gemfile: .gemfile
