---
sudo: false
language: ruby
bundler_args: --without system_tests
script: 'bundle exec rake spec'
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.4
      env: PUPPET_VERSION=4.10.9
    - rvm: 2.3.4
      env: PUPPET_VERSION=5.3.3
branches:
  only:
    - master
    - develop
notifications:
  email: false
gemfile: .gemfile
