---
  language: ruby
  rvm:
    - 2.1
    - 2.2
    - 2.3
    - 2.4
  script: 'rake spec'
  branches:
    only:
      - master
  env:
    - PUPPET_VERSION=4.8.1
    - PUPPET_VERSION=4.8.0
  notifications:
    email:
      - javier.juarez@gmail.com
    gemfile: .gemfile

