image: ruby:2.1.10

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - ruby --version
          - bundler --version
          - bundle install
          - bundle exec rake test

